run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - gocritic
    - forbidigo
    - misspell

linters-settings:
  forbidigo:
    forbid:
      - p: os\.Exit
        msg: "use error return instead of os.Exit in library code"
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

issues:
  exclude-dirs:
    - migrations
    - vendor
    - .go
  exclude-rules:
    - path: cmd/
      linters:
        - forbidigo
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
